#!/usr/bin/env node
/**
 * Generate the Codex native-plugin side from the Claude Code artefacts.
 *
 *   node codex/native-plugin.mjs [--plugin <dir>] [--emit-only] [--dry-run]
 *   node codex/native-plugin.mjs --top-level-profile native-ultra --out <codex-home>
 *
 * Codex discovers `.codex-plugin/plugin.json` before `.claude-plugin/plugin.json`. Without
 * this file it loaded `agents/*.md` as-is, including `model: haiku` / `model: opus`. Those
 * are Claude families. Codex has no haiku; the cheap-model fallback is Spark, whose rate-limit
 * bucket is `codex_bengalfox` ("Bengal Fox") — not the user's own Codex/Pro window.
 *
 * Native agents are Codex role TOML generated through the same translator as the clone fallback.
 * Markdown `model`/`effort` frontmatter is not a Codex role-config interface; TOML `model` and
 * `model_reasoning_effort` are. Neither route silently inherits the session model for a canonical
 * Graph Powers agent.
 *
 *   .codex-plugin/plugin.json           <- .claude-plugin/plugin.json
 *   .codex-plugin/marketplace.json      <- .claude-plugin/marketplace.json
 *   codex/native-agents/<name>.toml     <- agents/<name>.md (Codex policy resolved)
 */

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { agentToToml } from "./install.mjs";
import { readJson, tomlString, writeFile } from "./lib.mjs";
import { resolveCodexTopLevelProfile } from "./model-policy.mjs";

const HERE = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const NATIVE_AGENTS_DIR = "codex/native-agents";

function pluginRootFromArgv(argv) {
  const i = argv.indexOf("--plugin");
  if (i !== -1 && argv[i + 1] && !argv[i + 1].startsWith("-")) return resolve(argv[i + 1]);
  return HERE;
}

export function buildPluginManifest(claudeManifest) {
  return {
    name: claudeManifest.name,
    displayName: claudeManifest.displayName ?? "Graph Powers",
    description: claudeManifest.description,
    version: claudeManifest.version,
    author: claudeManifest.author,
    homepage: claudeManifest.homepage,
    repository: claudeManifest.repository,
    license: claudeManifest.license,
    keywords: [...new Set([...(claudeManifest.keywords ?? []), "codex"])],
    skills: "./skills/",
    agents: `./${NATIVE_AGENTS_DIR}/`,
    commands: "./commands/",
    hooks: "./hooks/hooks.json",
  };
}

export function buildMarketplace(claudeMarketplace) {
  return {
    name: claudeMarketplace.name ?? "graph-powers",
    description: claudeMarketplace.description,
    owner: claudeMarketplace.owner,
    plugins: (claudeMarketplace.plugins ?? []).map((plugin) =>
      Object.assign({}, plugin, { source: plugin.source ?? "./" }),
    ),
  };
}

export function listAgentFiles(pluginRoot) {
  const dir = join(pluginRoot, "agents");
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter((f) => f.endsWith(".md")).sort();
}

export function buildNativeAgents(pluginRoot, settings = {}, log = () => {}) {
  const files = {};
  for (const file of listAgentFiles(pluginRoot)) {
    const src = readFileSync(join(pluginRoot, "agents", file), "utf8");
    const toml = agentToToml(src, settings, log);
    if (toml) files[`${basename(file, ".md")}.toml`] = toml;
  }
  return files;
}

/** Render a Codex v2 top-level profile file. This path is deliberately separate from agent TOML:
 *  `codex --profile <name>` layers `<name>.config.toml` onto the parent session, while subagent
 *  roles are loaded from `agents.<role>.config_file`. Mixing the two would make Ultra recursive. */
export function topLevelProfileToToml(profileName, settings = {}) {
  const profile = resolveCodexTopLevelProfile(profileName, settings);
  return [
    `# Generated by graph-powers from codex/model-policy.json (${profile.profile}).`,
    "# Top-level only: do not combine with Graph Powers deterministic fan-out workflows.",
    `model = ${tomlString(profile.model)}`,
    `model_reasoning_effort = ${tomlString(profile.reasoningEffort)}`,
    "",
  ].join("\n");
}

export function emitTopLevelProfile({
  profileName,
  settings = {},
  outDir,
  dryRun = false,
  log = () => {},
} = {}) {
  if (!outDir) throw new Error("--top-level-profile requires --out <codex-home>");
  const contents = topLevelProfileToToml(profileName, settings);
  const path = join(resolve(outDir), `${profileName}.config.toml`);
  if (dryRun) log(`(dry-run) would emit ${path}`);
  else {
    writeFile(path, contents);
    log(path);
  }
  return { path, contents, written: dryRun ? [] : [path] };
}

/** `--models heavy=gpt-5.6-sol,light=gpt-5.6-luna` -> `{ heavy, light }`. Unknown tiers are refused
 *  rather than ignored: a typo that silently writes nothing is the failure this flag exists to fix. */
export function parseModelsFlag(spec) {
  if (!spec) return null;
  const models = {};
  for (const pair of String(spec).split(",")) {
    const [tier, slug] = pair.split("=").map((x) => (x ?? "").trim());
    if (!tier) continue;
    if (!["heavy", "standard", "light"].includes(tier))
      throw new Error(`unknown tier "${tier}" — expected heavy, standard or light`);
    if (!slug) throw new Error(`tier "${tier}" has no model slug`);
    models[tier] = slug;
  }
  return Object.keys(models).length ? models : null;
}

export function install({
  pluginRoot = HERE,
  dryRun = false,
  emit = false,
  emitOnly = false,
  models = null,
  codexSettings = null,
  outDir = null,
  log = () => {},
} = {}) {
  const written = [];
  const claudeManifest = readJson(join(pluginRoot, ".claude-plugin/plugin.json"), {});
  const claudeMarketplace = readJson(join(pluginRoot, ".claude-plugin/marketplace.json"), {});
  const pluginManifest = buildPluginManifest(claudeManifest);
  const marketplace = buildMarketplace(claudeMarketplace);
  const settings = codexSettings ?? (models ? { models } : {});
  const agents = buildNativeAgents(pluginRoot, settings, log);
  // Where the agents land. Tracked defaults are generated from the repository policy; an operator
  // can render project/profile overrides into a separate directory with `--config ... --out ...`.
  const agentsRoot = outDir ? resolve(outDir) : join(pluginRoot, NATIVE_AGENTS_DIR);

  if (emit || emitOnly) {
    // With `--out` the caller asked for THEIR agents, not a second copy of the plugin: the two
    // manifests describe the tracked layout (`./codex/native-agents/`) and would be wrong anywhere
    // else, so they are emitted for the tracked destination only.
    const paths = [
      ...(outDir
        ? []
        : [
            [
              join(pluginRoot, ".codex-plugin/plugin.json"),
              `${JSON.stringify(pluginManifest, null, 2)}\n`,
            ],
            [
              join(pluginRoot, ".codex-plugin/marketplace.json"),
              `${JSON.stringify(marketplace, null, 2)}\n`,
            ],
          ]),
      ...Object.entries(agents).map(([file, body]) => [
        join(agentsRoot, file),
        body.endsWith("\n") ? body : `${body}\n`,
      ]),
    ];
    for (const [path, contents] of paths) {
      if (dryRun) {
        log(`(dry-run) would emit ${path}`);
        continue;
      }
      writeFile(path, contents);
      written.push(path);
      log(path);
    }
  }

  return { written, pluginManifest, marketplace, agents };
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  const argv = process.argv.slice(2);
  const flag = (name) => {
    const i = argv.indexOf(name);
    return i !== -1 && argv[i + 1] && !argv[i + 1].startsWith("-") ? argv[i + 1] : null;
  };
  const models = parseModelsFlag(flag("--models"));
  const configPath = flag("--config");
  const outDir = flag("--out");
  const topLevelProfile = flag("--top-level-profile");
  if ((models || configPath || topLevelProfile) && !outDir) {
    console.error(
      "--models/--config/--top-level-profile require --out <dir>: operator overrides must not replace the tracked semantic defaults.",
    );
    process.exit(1);
  }
  if (topLevelProfile && models) {
    console.error("--models configures subagent tiers and cannot be combined with --top-level-profile.");
    process.exit(1);
  }
  let codexSettings = {};
  if (configPath) {
    const parsed = JSON.parse(readFileSync(resolve(configPath), "utf8"));
    codexSettings = parsed?.codex && typeof parsed.codex === "object" ? parsed.codex : parsed;
    if (!codexSettings || typeof codexSettings !== "object") {
      throw new Error("--config must contain a JSON object or a top-level codex object");
    }
  }
  if (models) codexSettings = { ...codexSettings, models: { ...codexSettings.models, ...models } };
  if (topLevelProfile) {
    const result = emitTopLevelProfile({
      profileName: topLevelProfile,
      settings: codexSettings,
      outDir,
      dryRun: argv.includes("--dry-run"),
      log: (m) => console.log(`  ${m}`),
    });
    if (!argv.includes("--dry-run") && result.written.length) {
      console.log(`codex-native: top-level profile ${topLevelProfile} written`);
    }
    process.exit(0);
  }
  const result = install({
    pluginRoot: pluginRootFromArgv(argv),
    dryRun: argv.includes("--dry-run"),
    emit: true,
    emitOnly: true,
    codexSettings,
    outDir,
    log: (m) => console.log(`  ${m}`),
  });
  if (!argv.includes("--dry-run") && result.written.length) {
    console.log(`codex-native: ${result.written.length} path(s) written`);
  }
}
